version: '3'

services:
  ros-rosbridge-suite:
    image: ghcr.io/helix-robotics-ag/ros-rosbridge-suite:iron
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    ipc: host
    pid: host
    environment:
      - UID=${HOST_UID}
      - ROS_DOMAIN_ID
    command: su - ros --whitelist-environment=ROS_DOMAIN_ID /run.sh
